# Backend Values

enabled: true
replicaCount: 1

image:
  repository: teletubbies-backend
  tag: v1.0.0
  pullPolicy: Never 

initDbImage: mariadb:10.6.12  

service:
  type: ClusterIP
  port: 8080 
  targetPort: 8080 

db:
  host: teletubbies-db 
  port: 3306 
  name: san_martino_friendship_day 

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "400m"
    memory: "1Gi"

probes:
  liveness:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 20
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10