frontend:
  enabled: true
  replicaCount: 3
  
  # Immagine
  image:
    repository: teletubbies-frontend
    tag: v1.0.1
    pullPolicy: Never # Utile per i test in Minikube

  # Service
  service:
    port: 80
    targetPort: 80
    type: ClusterIP
    
  # Risorse
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

ingress:
  enabled: true
  className: "nginx"
  host: progetto.teletubbies.com
  # Riferimenti al Service del Backend (usando il nome completo risolto da Helm)
  backendServicePort: 8080
