apiVersion: v1
kind: Service
metadata:
  name: teletubbies-backend
  labels:
    app: teletubbies
    component: backend
spec:
  selector:
    component: backend
  ports:
    - protocol: TCP
      port: 8080        # La porta che espone il Service nel cluster
      targetPort: 8080  # La porta a cui punta nei container
  type: ClusterIP      # Accessibile solo dall'interno del cluster (es. dal Frontend)