apiVersion: v1
kind: Secret
metadata:
  name: teletubbies-db-creds
  labels:
    app: teletubbies
    component: db
type: Opaque
stringData:
  # MARIADB_USER: root -> "cm9vdA==" in base64
  DB_USER: root
  # MARIADB_PASSWORD: mysecretpassword -> "bXlzZWNyZXRwYXNzd29yZA==" in base64
  DB_PASSWORD: mysecretpassword
