trigger:
- "*"

variables:
  system.debug: true
  FRONTEND_URL_API: 'http://localhost:8081/api/submission'
  FRONTEND_URL_E2E: 'http://localhost:8081'
  BACKEND_URL_API: 'http://localhost:8080/api/submission'
  BACKEND_URL: 'http://localhost:8080/health'
  TEST_DATA: >
    {"name":"Andrea",
    "surname":"Grossi",
    "gender":"man",
    "email":"xhunterx92@gmail.com",
    "residencyCountry":"italy",
    "fiscalCode":"GRSNRF92L31F205T",
    "residencyZipCode":"20031",
    "residencyAddress":"Via Enrico Berlinguer, 11",
    "shipCountry":"italy",
    "shipZipCode":"20031",
    "shipAddress":"Via Enrico Berlinguer, 11",
    "privacy":true,
    "rules":true,"birthDate":"1992-07-31",
    "phoneNumber":"3408461295",
    "residencyProvince":"MI",
    "shipProvince":"MI"}
  ECR_REGISTRY: '089648475292.dkr.ecr.eu-south-1.amazonaws.com'
  ECR_REGION: 'eu-south-1'

jobs:
- job: Pipeline
  displayName: 'End-to-end Pipeline'
  pool:
    vmImage: 'ubuntu-latest'
  steps: 
    # Setup servizi Docker
    - template: templates/setup-services.yaml
    
    # Esegui tutti i test
    - template: templates/run-tests.yaml
    
    # Push immagini su ECR
    - template: templates/push-to-ecr.yaml

    # Pulizia finale
    - script: docker-compose down -v
      displayName: 'Stop docker compose'
