trigger:
  branches:
    include:
      - main
      - 'feature/*'

variables:
  # Variabili in linea definite come elementi di una lista
  - name: system.debug
    value: true
  - name: FRONTEND_URL_API
    value: 'http://localhost:8081/api/submission'
  - name: FRONTEND_URL_E2E
    value: 'http://localhost:8081'
  - name: BACKEND_URL_API
    value: 'http://localhost:8080/api/submission'
  - name: BACKEND_URL
    value: 'http://localhost:8080/health'
  
  # Variabile TEST_DATA
  - name: TEST_DATA
    value: |
      {"name":"Andrea",
      "surname":"Grossi",
      "gender":"man",
      "email":"xhunterx92@gmail.com",
      "residencyCountry":"italy",
      "fiscalCode":"GRSNRF92L31F205T",
      "residencyZipCode":"20031",
      "residencyAddress":"Via Enrico Berlinguer, 11",
      "shipCountry":"italy",
      "shipZipCode":"20031",
      "shipAddress":"Via Enrico Berlinguer, 11",
      "privacy":true,
      "rules":true,"birthDate":"1992-07-31",
      "phoneNumber":"3408461295",
      "residencyProvince":"MI",
      "shipProvince":"MI"}

  # Variabili ECR
  - name: ECR_REGISTRY
    value: '089648475292.dkr.ecr.eu-south-1.amazonaws.com'
  - name: ECR_REGION
    value: 'eu-south-1'
  
  # Riferimento al gruppo di variabili AWS
  - group: aws-credentials 

jobs:
- job: Pipeline
  displayName: 'End-to-end Pipeline'
  pool:
    vmImage: 'ubuntu-latest'
  steps: 
    # Setup servizi Docker
    - template: templates/setup-services.yaml
    
    # Esegui tutti i test
    - template: templates/run-tests.yaml
    
    # Push immagini su ECR
    - template: templates/push-to-ecr.yaml

    # Pulizia finale
    - script: docker-compose down -v
      displayName: 'Stop docker compose'
