# azure-pipelines.yml

trigger:
  - "*"

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: "cd Front-End && docker build ."
    displayName: 'build Frontend image'

  - script: "cd Back-End/sanmartino-friendship-day && docker build ."
    displayName: 'build Backend image'

  - script: "cd Database && docker build ."
    displayName: 'build Database image'
