trigger:
- "*"

variables:
  system.debug: true
  FRONTEND_URL_API: 'http://localhost:8081/api/submission'
  FRONTEND_URL_E2E: 'http://localhost:8081'
  BACKEND_URL_API: 'http://localhost:8080/api/submission'
  BACKEND_URL: 'http://localhost:8080/health'
  TEST_DATA: >
    {"name":"Andrea",
    "surname":"Grossi",
    "gender":"man",
    "email":"xhunterx92@gmail.com",
    "residencyCountry":"italy",
    "fiscalCode":"GRSNRF92L31F205T",
    "residencyZipCode":"20031",
    "residencyAddress":"Via Enrico Berlinguer, 11",
    "shipCountry":"italy",
    "shipZipCode":"20031",
    "shipAddress":"Via Enrico Berlinguer, 11",
    "privacy":true,
    "rules":true,"birthDate":"1992-07-31",
    "phoneNumber":"3408461295",
    "residencyProvince":"MI",
    "shipProvince":"MI"}

jobs:
- job: Pipeline
  displayName: 'End-to-end Pipeline'
  pool:
    vmImage: 'ubuntu-latest'
  steps: 
    # Avvia i servizi e attendi che siano pronti
    - template: tests/setup-services.yaml
    
    # Aggiungi i wait per assicurare che i servizi siano online
    - script: |
        set -x
        echo "Waiting 20 seconds for services to fully initialize..."
        sleep 20 # Aumenta il tempo di attesa
        echo "Starting availability tests..."
        echo "Waiting for frontend..."
        until curl -s -o /dev/null -w '%{http_code}' $(FRONTEND_URL_E2E) | grep -q '200'; do
          echo "$(date '+%Y-%m-%d %H:%M:%S') - Frontend not ready, retrying..."
          sleep 2
        done
        echo "Frontend is ready!"

        echo "Waiting for backend..."
        until curl -s -o /dev/null -w '%{http_code}' $(BACKEND_URL) | grep -q '200'; do
          echo "$(date '+%Y-%m-%d %H:%M:%S') - Backend not ready, retrying..."
          sleep 2
        done
        echo "Backend is ready!"
      displayName: 'Wait for services'

    # Esegui i test di integrazione API e database
    - template: tests/integration-tests/api-tests.yaml
    
    # Esegui i test E2E con Playwright
    - template: tests/integration-tests/e2e-tests.yaml
    
    # Pulizia finale
    - script: docker-compose down
      displayName: 'Stop docker compose'
