# azure-pipelines.yml

trigger:
  - "*"

pool:
  vmImage: 'ubuntu-latest'

variables:
  FRONTEND_URL: 'http://localhost:8081/api/submission' 
  BACKEND_URL: 'http://localhost:8080/api/submission' 
  TEST_DATA: '{"name":"Andrea","surname":"Grossi","gender":"man","email":"xhunterx92@gmail.com","residencyCountry":"italia","fiscalCode":"GRSNRF92L31F205T","residencyZipCode":"20031","residencyAddress":"Via Enrico Berlinguer, 11","shipCountry":"Italia","shipZipCode":"20031","shipAddress":"Via Enrico Berlinguer, 11","privacy":true,"rules":true,"birthDate":"1992-07-31","phoneNumber":"3408461295","residencyProvince":"MI","shipProvince":"MI"}'
              
steps:
# Install Docker compose
  - script: |
      sudo apt-get update
      sudo apt-get install -y docker-compose
    displayName: 'Install docker compose'

# Build & Start Containers
  - script: |
      docker-compose down -v
      docker-compose up --build -d
            
      # Ciclo di attesa per il backend

      echo "Waiting for backend service to be healthy..."

      for i in $(seq 1 30); do
        if docker-compose ps backend | grep "healthy" > /dev/null; then
          echo "Backend is healthy!"
          break
        fi
        echo "Waiting... ($i/30)"
        sleep 2
      done

      # Ciclo di attesa per il frontend

      echo "Waiting for frontend service to be healthy..."

      for i in $(seq 1 30); do
        if docker-compose ps frontend | grep "healthy" > /dev/null; then
          echo "Frontend is healthy!"
          break
        fi
        echo "Waiting... ($i/30)"
        sleep 2
      done
    displayName: 'Start docker compose and wait for services'

# Test API Backend
  - script: |
      set -x
      RESPONSE=$(curl -s -o temp.json -w "%{http_code}" \
        -X POST "$(BACKEND_URL)" \
        -H "Content-Type: application/json" \
        -d '$(TEST_DATA)')

      echo "HTTP Status: $RESPONSE"
      echo "Response body:"
      cat temp.json

      if [ "$RESPONSE" = "201" ] && grep -q "submission successful" temp.json; then
        echo "OK: Test backend superato"
      else
        echo "FAIL: Test backend fallito"
        exit 1
      fi
    displayName: 'Integration Test - Backend API'

# Test API Frontend
  - script: |
      RESPONSE=$(curl -s -o temp_front.json -w "%{http_code}" \
        -X POST "$(FRONTEND_URL)" \
        -H "Content-Type: application/json" \
        -d '$(TEST_DATA)')

      echo "HTTP Status: $RESPONSE"
      echo "Response body:"
      cat temp_front.json

      if [ "$RESPONSE" = "201" ] && grep -q "submission successful" temp_front.json; then
        echo "OK: Test frontend superato"
      else
        echo "FAIL: Test frontend fallito"
        exit 1
      fi
    displayName: 'Integration Test - Frontend API'

# Duplicate User Test (Negative Result)
  - script: |
      curl -X POST "$(FRONTEND_URL)" \
      -H 'Content-Type: application/json' \
      --data-raw '$(TEST_DATA)'
    displayName: 'Integration Test - Frontend API (Negative)'

# Install MySQL client
  - script: |
      sudo apt-get update
      sudo apt-get install -y mysql-client
    displayName: 'Install MySQL Client'  

# Direct Database to verify created Users
  - script: |     
      mysql -h localhost -u root -pmysecretpassword san_martino_friendship_day \
      -e "SELECT * FROM customers WHERE email='xhunterx92@gmail.com';"
    displayName: 'Verify Test User via MySQL Client' 


# Install playwright
  - script: |
      npm install playwright
      npx playwright install
    displayName: 'Install Playwright' 

# Test End to End with Playwright

# Stop and cleanup the Container
  - script: docker-compose down
    displayName: 'Stop docker compose'