# values.yaml (Radice)

global:
  nameOverride: "teletubbies"
  labels:
    app.kubernetes.io/name: teletubbies-app
  secret:
    db:
      name: "teletubbies-db-creds" 

rootSecretCredentials:
  dbUser: "root"
  dbPassword: "mysecretpassword"

# CONFIGURAZIONE FRONTEND (SUBCHART)
frontend:
  enabled: true
  fullnameOverride: teletubbies-frontend
  replicaCount: 1
  image:
    repository: teletubbies-frontend
    tag: v1.0.0
    pullPolicy: Never 
  service:
    port: 80
  ingress:
    enabled: true
    host: "progetto.teletubbies.com"
    className: "nginx"

# CONFIGURAZIONE BACKEND (SUBCHART)
backend:
  enabled: true
  fullnameOverride: teletubbies-backend
  replicaCount: 1
  image:
    repository: teletubbies-backend
    tag: v1.0.0
    pullPolicy: Never
  service:
    port: 8080
    targetPort: 8080
    type: ClusterIP
  healthPath: "/health" 
  initDbImage: "mariadb:10.6.12" 
  # Configurazione di connessione al DB (usa il Service name del DB, definito nel subchart db)
  db:
    host: teletubbies-db 
    port: 3306
    name: san_martino_friendship_day
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "400m"
      memory: "1Gi"

# CONFIGURAZIONE DATABASE (SUBCHART)
db:
  enabled: true 
  fullnameOverride: teletubbies-db
  image: 
    repository: teletubbies-db
    tag: v1.0.0
    pullPolicy: Never 

  # Service
  service:
    port: 3306
    targetPort: 3306
    type: ClusterIP

  # Deployment
  databaseName: san_martino_friendship_day
  waitTimeout: "300"
  interactiveTimeout: "300"
  # Persistent Volume Claim
  pvc: 
    enabled: true
    storage: 5Gi
    accessModes: ReadWriteOnce 
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"