# values ambiente Prod

global:
  nameOverride: "teletubbies-prod"
  labels:
    # Etichetta ambiente
    app.kubernetes.io/environment: prod

  # creation Account (IRSA)
  serviceAccount:
    create: true
    name: "teletubbies-eks-deployer"

    # Annotazione IRSA che collega il SA al Ruolo IAM "ecr-pull-images"
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::089648475292:role/ecr-pull-images"
  db:
    enabled: false
    host: "decyda-dev-mariadb.c7w08masciuc.eu-south-1.rds.amazonaws.com"
    name: "decyda_dev_db"
    port: 3306

# Disabilita la creazione del secret locale (usiamo quello manuale per RDS)
dbSecret:
  create: false

backend:
  # SA Injection
  serviceAccount:
    name: "teletubbies-eks-deployer"

  # Immagine da ECR
  image:
    repository: 089648475292.dkr.ecr.eu-south-1.amazonaws.com/teletubbies-backend
    tag: v1.0.0
    pullPolicy: Always 
  
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

frontend:
  # SA Injection
  serviceAccount:
    name: "teletubbies-eks-deployer"

  # Immagine da ECR
  image:
    repository: 089648475292.dkr.ecr.eu-south-1.amazonaws.com/teletubbies-frontend
    tag: v1.0.0
    pullPolicy: Always
    
  ingress:
    enabled: true
    className: "nginx"
    host: "teletubbies-prod.dev.decyda.com"
    backendServicePort: 8080

    annotations:
      external-dns.alpha.kubernetes.io/hostname: "teletubbies-prod.dev.decyda.com"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
