# Configurazione Globale/Comune
global:
  nameOverride: "teletubbies"
  labels:
    app.kubernetes.io/name: teletubbies-app
    app.kubernetes.io/instance: ""
  secret:
    db:
      # Questo nome è quello che viene usato in k8s-secrets.yaml (teletubbies-db-creds)
      name: "teletubbies-db-creds" 

# --- SEZIONE SECRET PER CREAZIONE RISORSA K8S ---
# Questi valori vengono utilizzati solo per creare il Secret K8s nel Chart radice.
secret:
  dbUser: "root"
  dbPassword: "mysecretpassword"

# --- CONFIGURAZIONE FRONTEND (SUBCHART) ---
frontend:
  enabled: true
  replicaCount: 3
  image:
    repository: teletubbies-frontend
    tag: v1.0.0
    pullPolicy: Never # Per Minikube/immagini locali
  service:
    port: 80
  ingress:
    enabled: true
    host: "progetto.teletubbies.com" # Il dominio per l'Ingress
    className: "nginx"

# --- CONFIGURAZIONE BACKEND (SUBCHART) ---
backend:
  enabled: true
  replicaCount: 3
  
  image:
    repository: teletubbies-backend
    tag: v1.0.0
    pullPolicy: Never
    
  service:
    port: 8080
    targetPort: 8080
    type: ClusterIP
  healthPath: "/health" # Endpoint per Liveness/Readiness Probe
  initDbImage: "mariadb:10.6.12" # Immagine per l'Init Container
  # Configurazione di connessione al DB (usa il Service name del DB)
  db:
    # Service Host del DB (es. nome-release-db)
    host: teletubbies-db 
    port: 3306
    name: san_martino_friendship_day
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "400m"
      memory: "1Gi"
# --- CONFIGURAZIONE DATABASE (SUBCHART) ---
db:
  enabled: true 
  # Immagine
  image: 
    repository: teletubbies-db
    tag: v1.0.0
    pullPolicy: Never # Utile per i test in Minikube

  # Service
  service:
    port: 3306
    targetPort: 3306
    type: ClusterIP

  # Deployment
  databaseName: san_martino_friendship_day
  waitTimeout: "300"
  interactiveTimeout: "300"
  # Persistent Volume Claim
  # Se preferisci 'persistence', dovrai modificare anche i template del DB.
  pvc: 
    enabled: true
    storage: 5Gi
    accessModes: ReadWriteOnce 
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
