# values-Frontend-Prod-EKS
global:
  serviceAccount:
    name: "teletubbies-eks-deployer"

replicaCount: 3

image:
  repository: 089648475292.dkr.ecr.eu-south-1.amazonaws.com/teletubbies-frontend
  tag: v1.1.0 
  pullPolicy: Always

service:
  port: 80
  targetPort: 80
  type: ClusterIP

backend:
  serviceName: teletubbies-prod-backend-service
  servicePort: 8080

ingress:
  enabled: true
  className: "nginx"
  host: "teletubbies-prod.dev.decyda.com"
  backendServicePort: 8080
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "teletubbies-prod.dev.decyda.com"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
