{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "frontend.fullname" . }}-ingress
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
spec:
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      # 1. Regola API: Traffico a /api va al Service del Backend
      - path: /api
        pathType: Prefix
        backend:
          service:
            # CORREZIONE: Usa la funzione "fullname" del sub-chart backend
            # Questo risolve in "teletubbies-release-teletubbies-backend"
            name: {{ include "backend.fullname" . }} 
            port:
              number: {{ .Values.ingress.backendServicePort }}
      # 2. Regola di Default: Tutto il resto (/) va al Service del Frontend
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "frontend.fullname" . }}
            port:
              number: {{ .Values.frontend.service.port }}
{{- end }}