{{- if .Values.db.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secret.db.name }}
  labels:
    {{- include "teletubbies-web-app.labels" . | nindent 4 }}
type: Opaque
data:
  # MARIADB_USER/DB_USER (il nome della chiave deve corrispondere a quanto referenziato nei Deployment)
  DB_USER: {{ .Values.secret.dbUser | b64enc | quote }} 
  
  # MARIADB_ROOT_PASSWORD/DB_PASSWORD
  DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc | quote }}
{{- end }}