{{- if .Values.db.enabled }}
# Global Secrets

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secret.db.name }}
  labels:
    {{- include "teletubbies-web-app.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.rootSecretCredentials.dbUser | b64enc | quote }} 
  MARIADB_USER: {{ .Values.rootSecretCredentials.dbUser | b64enc | quote }}
  
  DB_PASSWORD: {{ .Values.rootSecretCredentials.dbPassword | b64enc | quote }}
  MARIADB_PASSWORD: {{ .Values.rootSecretCredentials.dbPassword | b64enc | quote }}

  DB_NAME: {{ .Values.db.databaseName | b64enc | quote }} 
  MARIADB_DATABASE: {{ .Values.db.databaseName | b64enc | quote }}
  MARIADB_ROOT_PASSWORD: {{ .Values.rootSecretCredentials.dbPassword | b64enc | quote }}
{{- end }}