{{- if .Values.dbSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secret.db.name }}
  labels:
    {{- include "teletubbies-web-app.labels" . | nindent 4 }}
type: Opaque
data:
  # DB_USER: "user" (base64)
  DB_USER: {{ .Values.secret.dbUser | b64enc | quote }}           
  # DB_PASSWORD: "password" (base64)
  DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc | quote }}   
  # DB_ROOT_PASSWORD: "rootpassword" (base64)
  DB_ROOT_PASSWORD: {{ .Values.secret.dbRootPassword | b64enc | quote }}
{{- end }}
