{{- if .Values.global.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "teletubbies-web-app.fullname" .) .Values.global.serviceAccount.name }}
  labels:
    {{- include "teletubbies-web-app.labels" . | nindent 4 }}
  
  {{- with .Values.global.serviceAccount.annotations }}
  {{- if . }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }} 
  
{{- if .Values.global.serviceAccount.imagePullSecrets }}
imagePullSecrets:
{{ toYaml .Values.global.serviceAccount.imagePullSecrets | indent 2 }}
{{- end }}
{{- end -}}