apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.global.serviceAccount.name }}
      {{- if .Values.initDbMigration }}
      initContainers:
      - name: initsql
        image: {{ .Values.initDbImage | default "mariadb:10.6.12" }}
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
        env:
        - name: DB_USER 
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.secret.db.name }}
              key: DB_USER             
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.secret.db.name }}
              key: DB_PASSWORD
        - name: MARIADB_HOST 
          value: {{ .Values.global.db.host | quote }}
        - name: DB_PORT 
          value: {{ .Values.global.db.port | default 3306 | quote }}
        - name: DB_NAME
          value: {{ .Values.global.db.name | quote }}
        volumeMounts:
        - name: db-schema-migration
          mountPath: /schema 
        command: ["/bin/bash", "-c"]
        args:
          - |
            echo "1. In attesa che il database ${MARIADB_HOST}:${DB_PORT} sia raggiungibile..."
            until mariadb -h ${MARIADB_HOST} -P ${DB_PORT} -u ${DB_USER} -p${DB_PASSWORD} -e "SELECT 1;" > /dev/null 2>&1; do
              echo "Database non ancora pronto, attesa 3 secondi..."
              sleep 3
            done

            echo "2. Database pronto. Caricamento dello schema init.sql nel database ${DB_NAME}..."
            mariadb -h ${MARIADB_HOST} -P ${DB_PORT} -u ${DB_USER} -p${DB_PASSWORD} ${DB_NAME} < /schema/init.sql
            
            if [ $? -eq 0 ]; then
                echo "Schema caricato con successo."
            else
                echo "ERRORE durante il caricamento dello schema."
                exit 1
            fi
      {{- end }}
      containers:
      - name: backend-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        env: 
        - name: DB_HOST
          value: {{ .Values.global.db.host | quote }}
        - name: DB_PORT
          value: {{ .Values.global.db.port | default 3306 | quote }}
        - name: DB_NAME
          value: {{ .Values.global.db.name | quote }}
        - name: DB_USER 
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.secret.db.name }}
              key: DB_USER             
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.secret.db.name }}
              key: DB_PASSWORD
        livenessProbe:
          httpGet:
            path: {{ .Values.healthPath | default "/health" }}
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 90
          periodSeconds: 20
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: {{ .Values.healthPath | default "/health" }}
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 15

      volumes:
      - name: db-schema-migration
        configMap:
          name: {{ include "db.fullname" . }}-schema-script
