apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    release: kube-stack
spec:
  # Forza la ricerca in tutti i namespace se necessario
  namespaceSelector:
    any: true 
  selector:
    matchLabels:
      # Usiamo l'unico label che siamo sicuri sia identico ovunque
      app.kubernetes.io/name: teletubbies-app
  endpoints:
  - port: http-backend
    path: /actuator/prometheus
    interval: 15s