apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }} # Nome del Service usato dal Frontend (proxy_pass)
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http-backend
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}